-- Smart Dealer · Seed SQL
-- Execute no Supabase SQL Editor: https://supabase.com/dashboard → SQL Editor

-- 1. Criar tabelas
CREATE TABLE IF NOT EXISTS "VendaMensal" ("id" TEXT NOT NULL PRIMARY KEY, "grupo" TEXT NOT NULL, "loja" TEXT NOT NULL, "modelo" TEXT NOT NULL, "mes" INTEGER NOT NULL, "ano" INTEGER NOT NULL, "quantidade" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "Meta" ("id" TEXT NOT NULL PRIMARY KEY, "grupo" TEXT NOT NULL UNIQUE, "carta" DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS "Estoque" ("id" TEXT NOT NULL PRIMARY KEY, "grupo" TEXT NOT NULL, "loja" TEXT NOT NULL, "modelo" TEXT NOT NULL, "chao" INTEGER NOT NULL DEFAULT 0, "transito" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "LeadMensal" ("id" TEXT NOT NULL PRIMARY KEY, "referencia" TEXT NOT NULL UNIQUE, "leads" INTEGER NOT NULL, "leadsUnicos" INTEGER NOT NULL, "tempoAtendMin" DOUBLE PRECISION NOT NULL, "tcaPct" DOUBLE PRECISION NOT NULL, "lcrGrupoPct" DOUBLE PRECISION NOT NULL, "diasConversao" DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS "NPSMensal" ("id" TEXT NOT NULL PRIMARY KEY, "referencia" TEXT NOT NULL, "tipo" TEXT NOT NULL, "scoreMensal" DOUBLE PRECISION NOT NULL, "scoreTrimestral" DOUBLE PRECISION NOT NULL, "promotores" DOUBLE PRECISION NOT NULL, "neutros" DOUBLE PRECISION NOT NULL, "detratores" DOUBLE PRECISION NOT NULL);

-- 2. Metas
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('c6exq44llcq23u2kjsze','ACJ',67) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('c90rb700ttwpj0imavfx','AVALON',73) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('c8636w4t4p5ctq8vfmus','CELMAR',311) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('cpyzlkk87ujitvunpxu','I9 MOTOS',210) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('c5d8l4utb2g4n54qvdrh','MOTO PINDA',50) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('cfqip33ot16nbm8o0us5','MOTO PRAIA',110) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('cvassh7smq5lte72ne5g','NIPPON MOTOS',160) ON CONFLICT ("grupo") DO NOTHING;
INSERT INTO "Meta" ("id","grupo","carta") VALUES ('cs5v7j47tpdrfm76y7i','NOBRE MOTOS',188) ON CONFLICT ("grupo") DO NOTHING;

-- 3. Vendas Nippon Bragança Paulista
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmkasqts3wqo724euzn','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',1,2025,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjn3uwcb0fkg7gs9eo6l','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',1,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjuxmv3ond6ppvg4ecxi','NIPPON MOTOS','Bragança Paulista','AEROX',1,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czv7p1d8df44o0ltoni','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',1,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyv9a0xfupvpkaamtnl','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',1,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfgmc6urtvfds4hqlo9a','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',1,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clfvjxat70e0lt8f0n5','NIPPON MOTOS','Bragança Paulista','FLUO ABS',1,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crjsq2jb2mk93e9yd7bb','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',1,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cl2edx8epnkdmqzdk3j2','NIPPON MOTOS','Bragança Paulista','NMAX',1,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cczkn1zepolhirwdfpb','NIPPON MOTOS','Bragança Paulista','R15 ABS',1,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ck2hhl7t541qled8d340','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',1,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2u8fud67hnl85wkmcd','NIPPON MOTOS','Bragança Paulista','XMAX 300',1,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c19uyxhul21ajun8tzbe','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',1,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cczo62rtlqdtcb01a0xi','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',2,2025,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crk3syyqx83ijngoy17m','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',2,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ckhs43gqvvrj1s9c4wy9','NIPPON MOTOS','Bragança Paulista','AEROX',2,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbbrx47jq87vwyyeixp8','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',2,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czqndsx9sctzybf4hgr','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',2,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7ishzewxaa8gwpp85el','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',2,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfgl456w7gfhcduvukw1','NIPPON MOTOS','Bragança Paulista','FLUO ABS',2,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czesb7akeku90dzg5v47','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',2,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbz50qtfpnzc2specndr','NIPPON MOTOS','Bragança Paulista','NMAX',2,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clb5pg1hc2vm1phuf6gb','NIPPON MOTOS','Bragança Paulista','R15 ABS',2,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cuwwiy03h7br2r7fuz2','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',2,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjft6vgzgvrotcll9tx','NIPPON MOTOS','Bragança Paulista','XMAX 300',2,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd7fmsbmc7d5o4h48a0g','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',2,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csjf6wvjl0dy8ag440s','NIPPON MOTOS','Bragança Paulista','TT-R 230',2,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz8qdsxcdtlgwp43n246','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',3,2025,21);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('catt2uvrfzn74cp2q3d','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',3,2025,13);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7nbahtxn0eil709809v','NIPPON MOTOS','Bragança Paulista','AEROX',3,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cigrmoq7z877f59aii9o','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',3,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6zcky3eixabzvwjgpu5','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',3,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdtlo1ioze7fs9bsjavh','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',3,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c9iiwt30oq7kt3lojlpc','NIPPON MOTOS','Bragança Paulista','FLUO ABS',3,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c89iruea6sbtpv2877db','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',3,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cm04a1cxa3qj9bxs4ook','NIPPON MOTOS','Bragança Paulista','NMAX',3,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cpl5n9o6kfgmleajvsr','NIPPON MOTOS','Bragança Paulista','R15 ABS',3,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('conkwg40gh59sj61gvf8','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',3,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cf0ijbmat84r71p14ar4','NIPPON MOTOS','Bragança Paulista','XMAX 300',3,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0o4ybxgz2gkk6s8utro','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',3,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cggbz2kyaa9rr7r4t23n','NIPPON MOTOS','Bragança Paulista','TT-R 230',3,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvzls7rqxpys6cnhm24u','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',4,2025,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cm3s3rwerc3rvrniva96','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',4,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c01xm6ar41ebe43qd599a','NIPPON MOTOS','Bragança Paulista','AEROX',4,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6b121ji04f4gx5e3bjf','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',4,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cw1p49dee7wjw2duafqe','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',4,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbiprpvqd4lkl6u246it','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',4,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6p0y4qyktpifq22r3tf','NIPPON MOTOS','Bragança Paulista','FLUO ABS',4,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyn1rvokkh7jznycktb','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',4,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ciue8u9rxnmfm9nqor9z','NIPPON MOTOS','Bragança Paulista','NMAX',4,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgspxesqv85nizuw9lfv','NIPPON MOTOS','Bragança Paulista','R15 ABS',4,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdx2fzgb4108l4qg4vrc','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',4,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0c13zyrizvjl619oftg1','NIPPON MOTOS','Bragança Paulista','XMAX 300',4,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5bi3blycv6dqao2isrw','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',4,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqpfj0bai8vm1sgmlxec','NIPPON MOTOS','Bragança Paulista','TT-R 230',4,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cggctldwa3ofghe0ch1j','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',5,2025,23);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6g9fvnlmwebf968uh7y','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',5,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cuiret7qv7kho61ahb7','NIPPON MOTOS','Bragança Paulista','AEROX',5,2025,13);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ceh0vfvf6alfhv5djqs','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',5,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctbuvmau0bqn4lnrat0g','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',5,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ci5s60g7wexfqmxp0wg6','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',5,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ceqe0g6i5ywpvyhgc8vj','NIPPON MOTOS','Bragança Paulista','FLUO ABS',5,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7u7i2doq6uo435s9k5r','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',5,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnkc9zq70avll7vtltva','NIPPON MOTOS','Bragança Paulista','NMAX',5,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyjg9rss7rgqdn217yj','NIPPON MOTOS','Bragança Paulista','R15 ABS',5,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxwvmnihz9wfsrsdx6uo','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',5,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cftf594af3aymwexw3a','NIPPON MOTOS','Bragança Paulista','XMAX 300',5,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cai464a2y8orrgdp15rt','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',5,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chfdtv478h5pajhizqrs','NIPPON MOTOS','Bragança Paulista','TT-R 230',5,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cp9cw8lsin6e03w9egbj','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',6,2025,19);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz3iwlpdvuoq4y30fv','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',6,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqecojw61pb8aqyuw44i','NIPPON MOTOS','Bragança Paulista','AEROX',6,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cpida8szwxnkvufz318v','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',6,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdl0hufm9nxsg06k0g69','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',6,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2cjhrz08nseskeyavxa','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',6,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxs80mrt8ofa3ucltme4','NIPPON MOTOS','Bragança Paulista','FLUO ABS',6,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctr1batuf96kuweegczh','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',6,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctdryjchsxip1og45w5s','NIPPON MOTOS','Bragança Paulista','NMAX',6,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cklaxc9w9h7g5xvfgakk','NIPPON MOTOS','Bragança Paulista','R15 ABS',6,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c1u0pku9yz7e13odm3em','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',6,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6rg1lguucfhysb2z78','NIPPON MOTOS','Bragança Paulista','XMAX 300',6,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4s28jlfgr1jqzqlubkh','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',6,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz77yv0g5y67d3wi77d','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',7,2025,26);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ct4zcdn06zufukmn8wz7','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',7,2025,16);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxmi4t19e2ud0jwv3g1k','NIPPON MOTOS','Bragança Paulista','AEROX',7,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu6zkmoeqilll6lh34yz','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',7,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7f3iwz2yjxsm3r4diu5','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',7,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crdur4tywys08qboojk','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',7,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7kntlfui3y4nk49u6im','NIPPON MOTOS','Bragança Paulista','FLUO ABS',7,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7tf4x1ybrwf6agqskw','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',7,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6c02gxmi4goaawrtr8a','NIPPON MOTOS','Bragança Paulista','NMAX',7,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c493b6dtmnqnvvi368t5','NIPPON MOTOS','Bragança Paulista','R15 ABS',7,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu60baafg7or3ddknkba','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',7,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgm75y88e08ax1jsaxny','NIPPON MOTOS','Bragança Paulista','XMAX 300',7,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyqlf4ukrhin3dya4jf','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',7,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cq9v77hesz4rzz3doxi','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',8,2025,26);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd0f88tg4ow8xtplc9l8','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',8,2025,16);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6emcdik7c4ggh6ujezg','NIPPON MOTOS','Bragança Paulista','AEROX',8,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0idiqcn1264qtdy2kra8','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',8,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfjchjeekswuyr09qnqm','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',8,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4s7fsnu0wg3jlj3yvyf','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',8,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c91tfv5zgk68cedkuscv','NIPPON MOTOS','Bragança Paulista','FLUO ABS',8,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cksg3buwd27gk2vyerw','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',8,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c857t4eet35t2so9vchf','NIPPON MOTOS','Bragança Paulista','NMAX',8,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czc42pp4hxt7fq9ab0l','NIPPON MOTOS','Bragança Paulista','R15 ABS',8,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cih1s96a812sl7u1z4gi','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',8,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c305mx6yedld2c8a299','NIPPON MOTOS','Bragança Paulista','XMAX 300',8,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgeg96tqpbviv2jwdhax','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',8,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cpjrf6ay2szlcztoqi5i','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',9,2025,24);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz05phywqkhyv11n1of','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',9,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfspjdvdr0r6id8xr8z2','NIPPON MOTOS','Bragança Paulista','AEROX',9,2025,13);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crvrchedwcns4vnrskf8','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',9,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cr2a8tfgl26bv5vrilf','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',9,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6jop14i05fugkng0hd4','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',9,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyjxxytuwdv30200l0k','NIPPON MOTOS','Bragança Paulista','FLUO ABS',9,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czwqe005vazzlgs50c6','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',9,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6rd3w9b45tphhbic4y5','NIPPON MOTOS','Bragança Paulista','NMAX',9,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5ujoc6rukg7ohrmpe1w','NIPPON MOTOS','Bragança Paulista','R15 ABS',9,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cwh4nvbtbitrp0ppvyq1','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',9,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ca8304x55r2wc6gbnew0','NIPPON MOTOS','Bragança Paulista','XMAX 300',9,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqhc8zgl2y7yd3fljh9','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',9,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('co769c2gp9g9w0dfjh1z','NIPPON MOTOS','Bragança Paulista','TT-R 230',9,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cw1lgi58b58eb42nactu','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',10,2025,24);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ce8fhu6wetefs0o38l65','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',10,2025,15);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvv2m0ag313h32ur2ow','NIPPON MOTOS','Bragança Paulista','AEROX',10,2025,13);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnua56p5tc2b1n22rpmg','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',10,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cui60xuussw9yo8wkw2n','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',10,2025,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cirn6hckm8k2ieaffje','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',10,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7ingxt93w7ajtmrth1e','NIPPON MOTOS','Bragança Paulista','FLUO ABS',10,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cof08xdf4zbe88mb4vc1','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',10,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu56cfu52iekx378vity','NIPPON MOTOS','Bragança Paulista','NMAX',10,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7klg8izfyx9tlvsb96c','NIPPON MOTOS','Bragança Paulista','R15 ABS',10,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cc7ywghwr9as473ysqat','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',10,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdvs39jbas4q8u1mi4gb','NIPPON MOTOS','Bragança Paulista','XMAX 300',10,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctne2nhb6bomlgbyxpv2','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',10,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdc1sf2roaegy0zxbxse','NIPPON MOTOS','Bragança Paulista','TT-R 230',10,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('craphzoa9bmo4qmau6qu','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',11,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clz3oj20c8wlo42kugw2','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',11,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cntp711q5dlrizjhaflg','NIPPON MOTOS','Bragança Paulista','AEROX',11,2025,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c37eoglodwyr2f5oaqz7','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',11,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ccob267i15wtyytaemiy','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',11,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8odyi08qozxi1plk3jh','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',11,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c845v9q3w5e6vx9xpien','NIPPON MOTOS','Bragança Paulista','FLUO ABS',11,2025,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxq2sxzc9g1aqt5cvdc1','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',11,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5af3rwewj6wrmcrr8et','NIPPON MOTOS','Bragança Paulista','NMAX',11,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crycosmle2laey0iuqh','NIPPON MOTOS','Bragança Paulista','R15 ABS',11,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ckaq9bjy7dth8gm2wny','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',11,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clsbibmen789ejiagwo9','NIPPON MOTOS','Bragança Paulista','XMAX 300',11,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ch6nvyfq1nb95yfbln16','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',11,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5qlqw4mx8vjlh8949h4','NIPPON MOTOS','Bragança Paulista','TT-R 230',11,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxamrrl6s8tfbma90iq3','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',12,2025,26);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmco4ntqvsrhwbpwdfym','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',12,2025,15);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cul8dgixvrcas7qzsyw7','NIPPON MOTOS','Bragança Paulista','AEROX',12,2025,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2nlzvm5j7lcbgkka94d','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',12,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvwyuwp1e45rzqx3zxyq','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',12,2025,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csixjqec18sflx4f0rxg','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',12,2025,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnjs0nss5z7fzhgfhcmy','NIPPON MOTOS','Bragança Paulista','FLUO ABS',12,2025,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfaxohj0df8qkmq28f4w','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',12,2025,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4jfeadhmh8v9cqkof73','NIPPON MOTOS','Bragança Paulista','NMAX',12,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyepc6rr83bqc61dz4n','NIPPON MOTOS','Bragança Paulista','R15 ABS',12,2025,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyfnl3pjg51fp7z5sth','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',12,2025,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctuqypxu8tj8vhuna114','NIPPON MOTOS','Bragança Paulista','XMAX 300',12,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czfpa54nrqqelyyq2pdx','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',12,2025,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfrs8s7zg8dm20utclhw','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',1,2026,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cru2v4y63j4fuf506682','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',1,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cwvxx65t9vkdzk8lc8hj','NIPPON MOTOS','Bragança Paulista','AEROX',1,2026,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c9oi99djquumeqbbjss0','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',1,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cntekzmufxb7mbmkk7y','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',1,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cn33r143743fcdwq0jiz','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',1,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7lki6l4gf5kz3gjltrv','NIPPON MOTOS','Bragança Paulista','FLUO ABS',1,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8ilfunqmbwodablg48h','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',1,2026,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ca0s6e0ur4sgyi8y7iqq','NIPPON MOTOS','Bragança Paulista','NMAX',1,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmrp75ohf6ne2ccxa4w4','NIPPON MOTOS','Bragança Paulista','R15 ABS',1,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c57qqcys3ufn9hjyf61o','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',1,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3f6uvr19embltcy4y9o','NIPPON MOTOS','Bragança Paulista','XMAX 300',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ct6njns12w1ojz1msp8','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvlbrv0epx3mwcmomdb','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',2,2026,17);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cual46ikxx5howj0zg8i','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',2,2026,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ccwbntaeanqkyht4x8v','NIPPON MOTOS','Bragança Paulista','AEROX',2,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfhtvqhski4500neytcj','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',2,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cakp3xjb77o7wvi2tv81','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',2,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cidyldnagb1j92aufk3y','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',2,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c1htripudj57gaguauys','NIPPON MOTOS','Bragança Paulista','FLUO ABS',2,2026,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('coyihqmbkvrra8yexfs7','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',2,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czqer69sf56mre868yjl','NIPPON MOTOS','Bragança Paulista','NMAX',2,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ch4tn2yjxx9endjwwr85','NIPPON MOTOS','Bragança Paulista','R15 ABS',2,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu4dpswt7gmda7pbp9fb','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',2,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu5x05es0nfejo9l7hq','NIPPON MOTOS','Bragança Paulista','XMAX 300',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csmmbwi4kgwt60eu9kd','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cn9sli1e9u78q19de8yf','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',3,2026,30);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cx56l10awiu5as2phxn','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',3,2026,18);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cn8y8pwsdv6afj7hfasr','NIPPON MOTOS','Bragança Paulista','AEROX',3,2026,17);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cm4fnfhxhzqhptiynose','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',3,2026,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cuy1h6phyg5kvbxwlg5','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',3,2026,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz8jvmkk1wjakfuk1vq2','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',3,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfaou0psb1asg4vky23','NIPPON MOTOS','Bragança Paulista','FLUO ABS',3,2026,11);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ciplxsgmhhpg0iwe61n7','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',3,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cltzgvpsy4scp05azszm','NIPPON MOTOS','Bragança Paulista','NMAX',3,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c864rtj9lbzjgn3y6zr','NIPPON MOTOS','Bragança Paulista','R15 ABS',3,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cg5teu1sa5i9rnlicui','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',3,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c488l6fp4ssk6elm458c','NIPPON MOTOS','Bragança Paulista','XMAX 300',3,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ciubjev7l9c98bkkx6bq','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',3,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0f8vqsgr76gpwxtdppkz','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',4,2026,26);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu67j4p31p2sta8ekoq','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',4,2026,16);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0hkxwray9q5id2wyavpq','NIPPON MOTOS','Bragança Paulista','AEROX',4,2026,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cm6v224oaaneoxhrsau','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',4,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cwp4tkvhojjserfk395','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',4,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cufe4sarquxm7zqu8wyu','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',4,2026,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgls1s6bxsgauki8pxdc','NIPPON MOTOS','Bragança Paulista','FLUO ABS',4,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cscfn20mp6wo5d8ap1qq','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',4,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chb56wac98odz1hltz6l','NIPPON MOTOS','Bragança Paulista','NMAX',4,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmflive9r8jtob0n0bz','NIPPON MOTOS','Bragança Paulista','R15 ABS',4,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cv7uwt5uvlrolhskk8kv','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',4,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csz7gnezgslr9pss4h0d','NIPPON MOTOS','Bragança Paulista','XMAX 300',4,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c067x03ra39fs74bkkxdf','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',4,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjrrq8xq1f1sqrelpr9f','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',5,2026,26);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0zzqq660a14ge54zbxio','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',5,2026,16);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7qxvnz1d6ym166x7bq2','NIPPON MOTOS','Bragança Paulista','AEROX',5,2026,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('coqil3v9f32gkizarww','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',5,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c480ox0mjjd9a1yxmlxw','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',5,2026,12);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cghey9jwk054vpe7vif','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',5,2026,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c31fhbp9ogmzhh240are','NIPPON MOTOS','Bragança Paulista','FLUO ABS',5,2026,9);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cg7lq10hbfou7m5ko98m','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',5,2026,8);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crwxm57dy4br6yqaksp0','NIPPON MOTOS','Bragança Paulista','NMAX',5,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cn2b47uj3wgb8io0w6t7','NIPPON MOTOS','Bragança Paulista','R15 ABS',5,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqeuy9icajkh9amk8gq','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',5,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('caf9606cnhte7xrczlat','NIPPON MOTOS','Bragança Paulista','XMAX 300',5,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbkx9qu70qn51vuukiq','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',5,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3m0i3nlh7vlh81hm7a8','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',6,2026,7);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6muqrwt4kuh8a1kcqjo','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',6,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyvxbi8mxlfl6bi2ky4','NIPPON MOTOS','Bragança Paulista','AEROX',6,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czedykrh9kbqtor4m6xh','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',6,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2693nyqgcxtixizkz3vu','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',6,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2n31fec0rdzhztn9q09','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',6,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cppwacod4y75t57mg2r','NIPPON MOTOS','Bragança Paulista','FLUO ABS',6,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5lfr35ynq8pg4gov4r5','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',6,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cts8u1waxcoowuxb8f3w','NIPPON MOTOS','Bragança Paulista','NMAX',6,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5955vwdfalkp66b1jr','NIPPON MOTOS','Bragança Paulista','R15 ABS',6,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cx6umg14v0g3ks238nb','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyhri9zj9cr92f2u7ph6','NIPPON MOTOS','Bragança Paulista','XMAX 300',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqkl1lbxh6j8qws3qoo','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',6,2026,1);

-- 4. Vendas Nippon Extrema
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c72088y2h2xtfx8jm1a9','NIPPON MOTOS','Extrema','FAZER 250 ABS',12,2025,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c50nup3xjf2t44hvkl7b','NIPPON MOTOS','Extrema','LANDER 250 ABS',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8vli0g1islfba5mjxmo','NIPPON MOTOS','Extrema','FACTOR 150 ED',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0sj7aikcxobffga3dtwr','NIPPON MOTOS','Extrema','NMAX',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3a6k9dm2v1st09lel38','NIPPON MOTOS','Extrema','AEROX',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbfutq2eeve4k0luc9c7','NIPPON MOTOS','Extrema','FACTOR 150 DX',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cxr07p1827wyuxe2jsh','NIPPON MOTOS','Extrema','R15 ABS',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cz6dcujdp2d4pt2kkwz','NIPPON MOTOS','Extrema','FLUO ABS',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2h0yp77lkyoym3e1off','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',12,2025,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cq0rluvpdjitu9z6v6wy','NIPPON MOTOS','Extrema','FAZER 250 ABS',1,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cx2ugnnibe48nj9az64f','NIPPON MOTOS','Extrema','LANDER 250 ABS',1,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cufqrphtqrtj1qrsxog9','NIPPON MOTOS','Extrema','FACTOR 150 ED',1,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu9rxhh4dgkio8fw8yf6','NIPPON MOTOS','Extrema','NMAX',1,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c192aqj4gz0c3511vvik','NIPPON MOTOS','Extrema','AEROX',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvp24s0esoynsvnwari','NIPPON MOTOS','Extrema','FACTOR 150 DX',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c84f8by6fbbn6gc9airr','NIPPON MOTOS','Extrema','R15 ABS',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cj8ifz1caovb2tyxhrt2','NIPPON MOTOS','Extrema','FLUO ABS',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdxmm1sy3y6ll2n7l1xr','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',1,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('coq74bqyfheersbuob9t','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',1,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjm7ym53au98f8shgt6w','NIPPON MOTOS','Extrema','XMAX 300',1,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5buerzbtileujdzmrfx','NIPPON MOTOS','Extrema','FAZER 250 ABS',2,2026,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu7ebejhdc3y8yq2hnv','NIPPON MOTOS','Extrema','LANDER 250 ABS',2,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ct4sqpkriz4ruc54sys','NIPPON MOTOS','Extrema','FACTOR 150 ED',2,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cs4o77ogv6y84axkaocu','NIPPON MOTOS','Extrema','NMAX',2,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgt0je5klx8dq4jvt4r','NIPPON MOTOS','Extrema','AEROX',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd5xq0p2oejntfcsf2zv','NIPPON MOTOS','Extrema','FACTOR 150 DX',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crqllp1ksu51hejuu3l','NIPPON MOTOS','Extrema','R15 ABS',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('coardzrkfc1jt77383kg','NIPPON MOTOS','Extrema','FLUO ABS',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clvknp6cp3mcemmgwyzp','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ccfrgqxx95in88hn550t','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7qb6q1k1kfmgidxbb3i','NIPPON MOTOS','Extrema','XMAX 300',2,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chkrwa4o9nb77g3wmz6i','NIPPON MOTOS','Extrema','FAZER 250 ABS',3,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvfku8acv3sgo8ils4fw','NIPPON MOTOS','Extrema','LANDER 250 ABS',3,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3dq7pd9sm5vvgip09ps','NIPPON MOTOS','Extrema','FACTOR 150 ED',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ckvuxr7480mif4x2kgr4','NIPPON MOTOS','Extrema','NMAX',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('choj75ms2v3laal06uq','NIPPON MOTOS','Extrema','AEROX',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cf877l0gyw7ewmj77ikg','NIPPON MOTOS','Extrema','FACTOR 150 DX',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c590lyyz5g7yfh3iw05j','NIPPON MOTOS','Extrema','R15 ABS',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cf7jy7cufqcl376ydh5y','NIPPON MOTOS','Extrema','FLUO ABS',3,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('comcmx592ukr6lxw9k0r','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',3,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdyob71gcrxf2z99212g','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',3,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqpyp4k3t4zpmq76og5','NIPPON MOTOS','Extrema','XMAX 300',3,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgk8pq9hfus84sge5q8d','NIPPON MOTOS','Extrema','FAZER 250 ABS',4,2026,5);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2htkv5sovjdj6nn98bd','NIPPON MOTOS','Extrema','LANDER 250 ABS',4,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cy339yr2wgr7i9kozdz','NIPPON MOTOS','Extrema','FACTOR 150 ED',4,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cp9grvl68m580aa3xb2a','NIPPON MOTOS','Extrema','NMAX',4,2026,3);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctwecal46370ghh4ty8','NIPPON MOTOS','Extrema','AEROX',4,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cniyoqzwor6pthaw775z','NIPPON MOTOS','Extrema','FACTOR 150 DX',4,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cn33vc46xdubjo3utl5f','NIPPON MOTOS','Extrema','R15 ABS',4,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5m8ws4eri2n17lq7pts','NIPPON MOTOS','Extrema','FLUO ABS',4,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgtljihckz734ddqm0a','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',4,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c9612fuh95ofejpsdr9x','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',4,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c1alsea9mqb56uj7h3uo','NIPPON MOTOS','Extrema','XMAX 300',4,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd5szqd7jxiveos2zq0e','NIPPON MOTOS','Extrema','FAZER 250 ABS',5,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ckvu4hj2acej4j5bgt2','NIPPON MOTOS','Extrema','LANDER 250 ABS',5,2026,4);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmj9aaxqdg6t6z7ig6r','NIPPON MOTOS','Extrema','FACTOR 150 ED',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cinf8p231e6lsaod7f','NIPPON MOTOS','Extrema','NMAX',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmaca6t66x1z6qfwqn2','NIPPON MOTOS','Extrema','AEROX',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ck962zj4xj69ynjah4y','NIPPON MOTOS','Extrema','FACTOR 150 DX',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnzvx5hhwghsmyagc9n','NIPPON MOTOS','Extrema','R15 ABS',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('citmaz9eu2fzdeime4g','NIPPON MOTOS','Extrema','FLUO ABS',5,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chrtm1gsm2c871cbs3bn','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',5,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czemvm4e2m7qpqidz6e','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',5,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cv2b98yayfzdyvw9k7ie','NIPPON MOTOS','Extrema','FAZER 250 ABS',6,2026,2);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c484wsiwryifxv6huwr8','NIPPON MOTOS','Extrema','LANDER 250 ABS',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6dmz4jio4q9iib3lbne','NIPPON MOTOS','Extrema','FACTOR 150 ED',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnymfv0m5kmah2h4gkbx','NIPPON MOTOS','Extrema','NMAX',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cs5c5tdpxqtmi1v6kbcq','NIPPON MOTOS','Extrema','AEROX',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cljurwxqqe9pnxjt6gg','NIPPON MOTOS','Extrema','FACTOR 150 DX',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cx4qq0yn5ztahcp7092','NIPPON MOTOS','Extrema','R15 ABS',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd1z0ruh0ejs2xnyg6xb','NIPPON MOTOS','Extrema','FLUO ABS',6,2026,1);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctj4zgkcvqbe5wlsu32','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',6,2026,1);

-- 5. Vendas regionais (totais por grupo)
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c98li4nbw4tnk47vk9yq','ACJ','ACJ','TOTAL',1,2025,40);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbmzmubdcc57wwnjrt6x','ACJ','ACJ','TOTAL',2,2025,39);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ccumd2ewa7brhhzwbkjh','ACJ','ACJ','TOTAL',3,2025,36);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chbqcg6r3xd901gkxoct','ACJ','ACJ','TOTAL',4,2025,33);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csfbmke0rjdavnlst5t9','ACJ','ACJ','TOTAL',5,2025,31);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c11nmgdzw5v221r8uuy','ACJ','ACJ','TOTAL',6,2025,29);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c77ayqy1865q0are203h','ACJ','ACJ','TOTAL',7,2025,29);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cwo8uc4spa88g5zp82gy','ACJ','ACJ','TOTAL',8,2025,31);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cw5lsl7bs6illsfc3j2','ACJ','ACJ','TOTAL',9,2025,33);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ct52kg9wl5xj1npxtpac','ACJ','ACJ','TOTAL',10,2025,36);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4svhxolb5ipgrxc1sji','ACJ','ACJ','TOTAL',11,2025,39);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cj3hfgm4dsm8i1uyt316','ACJ','ACJ','TOTAL',12,2025,40);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmoczysp3fa9xwrptl00','ACJ','ACJ','TOTAL',1,2026,40);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0kkq5scy1rhs006ol7i','ACJ','ACJ','TOTAL',2,2026,38);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0ykvskfs7votj0iy6g3','ACJ','ACJ','TOTAL',3,2026,36);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cirwzcutww8c3yuyiyim','ACJ','ACJ','TOTAL',4,2026,33);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2ah37m5l4difgfigelp','ACJ','ACJ','TOTAL',5,2026,30);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3n0j5sm4z2jbckmy82i','ACJ','ACJ','TOTAL',6,2026,10);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cw7olkxcqd1oud4xm151','AVALON','AVALON','TOTAL',1,2025,55);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0y4vk0q1vxx94ywnaed','AVALON','AVALON','TOTAL',2,2025,52);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ch5h2mm9ww17ogmyrrrw','AVALON','AVALON','TOTAL',3,2025,49);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cal40gnyqq8ugtlhlr8t','AVALON','AVALON','TOTAL',4,2025,45);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgecqvp20hqqhuq9zxnb','AVALON','AVALON','TOTAL',5,2025,42);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('critm60qy684e74d2db','AVALON','AVALON','TOTAL',6,2025,40);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfp029hdtympt1iwgtm','AVALON','AVALON','TOTAL',7,2025,40);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6gsht6qlors25oqu6kr','AVALON','AVALON','TOTAL',8,2025,41);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu70pbxmdap61czss9i','AVALON','AVALON','TOTAL',9,2025,45);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crtpdb3aaa5fnx3h9y9b','AVALON','AVALON','TOTAL',10,2025,49);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cyrb59h2ek6m0e9j4vc','AVALON','AVALON','TOTAL',11,2025,52);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c28k30vmuh9eopoz54ok','AVALON','AVALON','TOTAL',12,2025,55);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cen9fbyvj7iekvcgvod5','AVALON','AVALON','TOTAL',1,2026,54);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbkzeueb2uxp00pc2js','AVALON','AVALON','TOTAL',2,2026,52);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3qjci4nh983duorxyn8','AVALON','AVALON','TOTAL',3,2026,48);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8gz415th1tnpznvm0qh','AVALON','AVALON','TOTAL',4,2026,44);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmo4kw1xz6hr7rxzxjo','AVALON','AVALON','TOTAL',5,2026,41);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0kiubjtprcwmd8dybos','AVALON','AVALON','TOTAL',6,2026,14);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8nmlqkzfuplo7gqu529','CELMAR','CELMAR','TOTAL',1,2025,262);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('co3j5jrg507fbai4nfv','CELMAR','CELMAR','TOTAL',2,2025,251);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cl59ermg8qgewzyuxjgw','CELMAR','CELMAR','TOTAL',3,2025,234);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c2pqn0nzz3jumlmve85h','CELMAR','CELMAR','TOTAL',4,2025,216);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cmhyyqp1zz0h2b5b4isl','CELMAR','CELMAR','TOTAL',5,2025,200);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvctdidcfz8a9yxvkw1g','CELMAR','CELMAR','TOTAL',6,2025,190);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c99q6zi9f2swdgf3lvjn','CELMAR','CELMAR','TOTAL',7,2025,190);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c7xrtcngsr0tda10fy0i','CELMAR','CELMAR','TOTAL',8,2025,198);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdkjp6356cavj63u1k9c','CELMAR','CELMAR','TOTAL',9,2025,214);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('chd9bw5mcrl8mcynpzzb','CELMAR','CELMAR','TOTAL',10,2025,233);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cch1i4xovxyok6i1gda','CELMAR','CELMAR','TOTAL',11,2025,250);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crwwoc8inkmzkmluzes','CELMAR','CELMAR','TOTAL',12,2025,261);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cuykvca7tqkr0bcmrr3i','CELMAR','CELMAR','TOTAL',1,2026,260);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0u8m860t72brn9uhq826','CELMAR','CELMAR','TOTAL',2,2026,248);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csd3deb1uxno26hlq0q6','CELMAR','CELMAR','TOTAL',3,2026,231);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('czbgchamaf7own1e72n7','CELMAR','CELMAR','TOTAL',4,2026,212);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbkvynrs60mlyetzy82k','CELMAR','CELMAR','TOTAL',5,2026,197);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('clo6elnx8fngvisz027','CELMAR','CELMAR','TOTAL',6,2026,68);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cj62rkkzq1uue0v6739','I9 MOTOS','I9 MOTOS','TOTAL',1,2025,166);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cstg35lk2smc7hyqytaw','I9 MOTOS','I9 MOTOS','TOTAL',2,2025,159);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvifxr456ie6lwonj6a','I9 MOTOS','I9 MOTOS','TOTAL',3,2025,148);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csaiyajz886ss13n7w2','I9 MOTOS','I9 MOTOS','TOTAL',4,2025,137);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cf152klcjx8poikqx7g','I9 MOTOS','I9 MOTOS','TOTAL',5,2025,127);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cryxwksvd56nkuo96ux1','I9 MOTOS','I9 MOTOS','TOTAL',6,2025,121);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ck8o5z0yow0efjohu3gz','I9 MOTOS','I9 MOTOS','TOTAL',7,2025,120);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ctaxa7abuzzmu97rk0k','I9 MOTOS','I9 MOTOS','TOTAL',8,2025,126);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c31f5l8zolikpaoif0ef','I9 MOTOS','I9 MOTOS','TOTAL',9,2025,136);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cp3iwvwwlucfr46dmp0o','I9 MOTOS','I9 MOTOS','TOTAL',10,2025,147);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cykx2umzujp0rwy2eh1','I9 MOTOS','I9 MOTOS','TOTAL',11,2025,158);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cexmflrmtq0dv4h2chef','I9 MOTOS','I9 MOTOS','TOTAL',12,2025,166);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('co9c2bi11nhiet42epcy','I9 MOTOS','I9 MOTOS','TOTAL',1,2026,165);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c63qcwennpn33oammw8j','I9 MOTOS','I9 MOTOS','TOTAL',2,2026,157);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c48yijozkibrmwb7ucfe','I9 MOTOS','I9 MOTOS','TOTAL',3,2026,146);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c0ixerk98ycjejc7b11oe','I9 MOTOS','I9 MOTOS','TOTAL',4,2026,134);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4u9kug4xnwfwzzolpvs','I9 MOTOS','I9 MOTOS','TOTAL',5,2026,125);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu4031sopj4rrb8kw85e','I9 MOTOS','I9 MOTOS','TOTAL',6,2026,43);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdhlkxhdfj3cuik4g5c8','MOTO PINDA','MOTO PINDA','TOTAL',1,2025,25);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cunle8nj4ktrk3pqi2r','MOTO PINDA','MOTO PINDA','TOTAL',2,2025,24);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6z64ko35gq8oydm14z6','MOTO PINDA','MOTO PINDA','TOTAL',3,2025,22);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqorbf8g0z7f4nwufofq','MOTO PINDA','MOTO PINDA','TOTAL',4,2025,21);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('co022k7u2fedra5cdmem','MOTO PINDA','MOTO PINDA','TOTAL',5,2025,19);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3y197ztookmux0qfrz2','MOTO PINDA','MOTO PINDA','TOTAL',6,2025,18);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6w4e5cubpzqc7kibvz4','MOTO PINDA','MOTO PINDA','TOTAL',7,2025,18);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csy9ca563hddv4xft6l4','MOTO PINDA','MOTO PINDA','TOTAL',8,2025,19);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csguyrxno5map2tz8emn','MOTO PINDA','MOTO PINDA','TOTAL',9,2025,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ca88eqdnvm7l35w6ix','MOTO PINDA','MOTO PINDA','TOTAL',10,2025,22);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csyq0cp18s4se8kgrrjn','MOTO PINDA','MOTO PINDA','TOTAL',11,2025,24);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cbkgpgnvoh19ymftf1q','MOTO PINDA','MOTO PINDA','TOTAL',12,2025,25);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ciz5eo4kbzcruyxq0a5a','MOTO PINDA','MOTO PINDA','TOTAL',1,2026,25);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvvnupfki37y3jnkmtd','MOTO PINDA','MOTO PINDA','TOTAL',2,2026,24);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c31hhtgx99mjuvwongd9','MOTO PINDA','MOTO PINDA','TOTAL',3,2026,22);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c557alckkmu4cgytpf0p','MOTO PINDA','MOTO PINDA','TOTAL',4,2026,20);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cnin6ui2st8x2tx7m0s','MOTO PINDA','MOTO PINDA','TOTAL',5,2026,19);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cdzhihgpnr148cu4h5s','MOTO PINDA','MOTO PINDA','TOTAL',6,2026,6);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8pnero876koo01jhjrf','MOTO PRAIA','MOTO PRAIA','TOTAL',1,2025,71);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cek84vi6otna6etoae09','MOTO PRAIA','MOTO PRAIA','TOTAL',2,2025,68);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c9twumgk51u85nx6grcn','MOTO PRAIA','MOTO PRAIA','TOTAL',3,2025,63);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ct0lmata55xslv8kccus','MOTO PRAIA','MOTO PRAIA','TOTAL',4,2025,58);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cpjjpidalao8dxk172fx','MOTO PRAIA','MOTO PRAIA','TOTAL',5,2025,54);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cu8x624ouw907ix6yc0','MOTO PRAIA','MOTO PRAIA','TOTAL',6,2025,52);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c8jlnezb9t9ixlxxz4ep','MOTO PRAIA','MOTO PRAIA','TOTAL',7,2025,51);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('csrczg5j4azytfousio','MOTO PRAIA','MOTO PRAIA','TOTAL',8,2025,54);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c99ld6ylo558n7o83l7h','MOTO PRAIA','MOTO PRAIA','TOTAL',9,2025,58);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cfj1x90mfwek59zv91po','MOTO PRAIA','MOTO PRAIA','TOTAL',10,2025,63);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('crnna00gk2p8nrwpcrf','MOTO PRAIA','MOTO PRAIA','TOTAL',11,2025,68);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5hexj7p5xyfv3iktptr','MOTO PRAIA','MOTO PRAIA','TOTAL',12,2025,71);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('culkhbmitry49ibpqvp','MOTO PRAIA','MOTO PRAIA','TOTAL',1,2026,71);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c3fs4i002zjh5msogkkj','MOTO PRAIA','MOTO PRAIA','TOTAL',2,2026,67);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cki910qga5782dmbf3vn','MOTO PRAIA','MOTO PRAIA','TOTAL',3,2026,62);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cd62asxt9n6h1qf76ziv','MOTO PRAIA','MOTO PRAIA','TOTAL',4,2026,57);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cig7g4owatulocrlrbg0','MOTO PRAIA','MOTO PRAIA','TOTAL',5,2026,53);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ckxvsgf9w3fhwn7kr10','MOTO PRAIA','MOTO PRAIA','TOTAL',6,2026,18);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('ccosj7wxds888235gr8p','NOBRE MOTOS','NOBRE MOTOS','TOTAL',1,2025,98);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cx4u80te1o0ic4mydoez','NOBRE MOTOS','NOBRE MOTOS','TOTAL',2,2025,94);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c5y4fxrz04vhyigdyfh0','NOBRE MOTOS','NOBRE MOTOS','TOTAL',3,2025,87);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cgspw9pzik4evzlindi3','NOBRE MOTOS','NOBRE MOTOS','TOTAL',4,2025,80);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4if1wgp1mrh2gc23smu','NOBRE MOTOS','NOBRE MOTOS','TOTAL',5,2025,75);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c403cyozgy0t0ohpjyrt','NOBRE MOTOS','NOBRE MOTOS','TOTAL',6,2025,71);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c4ewn7v2u1bq2afp3r9e','NOBRE MOTOS','NOBRE MOTOS','TOTAL',7,2025,71);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cqbl55o8o7l70y6lgag','NOBRE MOTOS','NOBRE MOTOS','TOTAL',8,2025,74);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('co798kjp6zis6x7k0biy','NOBRE MOTOS','NOBRE MOTOS','TOTAL',9,2025,80);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvl7q4d02noqas8kq5i','NOBRE MOTOS','NOBRE MOTOS','TOTAL',10,2025,87);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c05yyp2l83cequxf3513','NOBRE MOTOS','NOBRE MOTOS','TOTAL',11,2025,93);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c03prdkya1fpxpie0ixx7','NOBRE MOTOS','NOBRE MOTOS','TOTAL',12,2025,97);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cv6gt08fmod7jaaz0814','NOBRE MOTOS','NOBRE MOTOS','TOTAL',1,2026,97);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c1h6mijb87r2cdilvr2b','NOBRE MOTOS','NOBRE MOTOS','TOTAL',2,2026,93);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cftc11ozwbsk3qn5lupi','NOBRE MOTOS','NOBRE MOTOS','TOTAL',3,2026,86);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cvvzzimt73okpuwx5npi','NOBRE MOTOS','NOBRE MOTOS','TOTAL',4,2026,79);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('cjqjjtcms5mi128kgism','NOBRE MOTOS','NOBRE MOTOS','TOTAL',5,2026,74);
INSERT INTO "VendaMensal" ("id","grupo","loja","modelo","mes","ano","quantidade") VALUES ('c6itx4b09u03pk4t2ri2','NOBRE MOTOS','NOBRE MOTOS','TOTAL',6,2026,25);

-- 6. Estoque Nippon Bragança Paulista
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cird6045pquf2kjomsoi','NIPPON MOTOS','Bragança Paulista','AEROX',0,3);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('czaritg7gytj72xfjbq','NIPPON MOTOS','Bragança Paulista','CROSSER 150 S ABS',1,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cjli0n0je8a8xc51pikz','NIPPON MOTOS','Bragança Paulista','CROSSER 150 Z ABS',10,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('ckpeomfo769dyplrcc5c','NIPPON MOTOS','Bragança Paulista','FACTOR 150 DX',0,8);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cmmy9z6jfvf9ym2pv4hv','NIPPON MOTOS','Bragança Paulista','FACTOR 150 ED',0,10);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c5klanwetz2wv4l2uer5','NIPPON MOTOS','Bragança Paulista','FAZER 250 ABS',9,13);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cywo7d5t7icvgwjnmzr','NIPPON MOTOS','Bragança Paulista','FLUO ABS',5,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c9of6h63a5nlhzo7vyg','NIPPON MOTOS','Bragança Paulista','FAZER FZ15 ABS',4,10);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cv88o1ezv0uomh5613e9','NIPPON MOTOS','Bragança Paulista','LANDER 250 ABS',6,2);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cicz2tc2t18h2vpv9d9','NIPPON MOTOS','Bragança Paulista','MT-03 ABS',0,3);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cf0w4xobu45778x2y02q','NIPPON MOTOS','Bragança Paulista','MT-07 ABS',0,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c6uqrlpv2axmawlqqr4o','NIPPON MOTOS','Bragança Paulista','NMAX',3,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c6hsdq24vhrpzhafspmu','NIPPON MOTOS','Bragança Paulista','R15 ABS',3,4);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('ccvcm7785vv4c6wzdb0g','NIPPON MOTOS','Bragança Paulista','R3 ABS',1,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cmrvnh2ih33eh2f8yf96','NIPPON MOTOS','Bragança Paulista','TÉNÉRÉ 700',1,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cpfu3vomwvp9u954r3b7','NIPPON MOTOS','Bragança Paulista','TT-R 230',0,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c1g9wskmi6rupgtkncoe','NIPPON MOTOS','Bragança Paulista','XMAX 300',6,4);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('ccky9ffxinznsgmhyb4b','NIPPON MOTOS','Bragança Paulista','YAMAHA ZR',1,5);

-- 7. Estoque Nippon Extrema
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('chq10lzcu1lj2xn553mk','NIPPON MOTOS','Extrema','AEROX',1,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c0xj9vr8swim28tfid1c','NIPPON MOTOS','Extrema','CROSSER 150 S ABS',0,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('ch0mjmpt62amvzzu096t','NIPPON MOTOS','Extrema','CROSSER 150 Z ABS',0,2);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cef3djnji33li7svt1lq','NIPPON MOTOS','Extrema','FACTOR 150 ED',1,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cqwxlzmalm8eg7wxoxnn','NIPPON MOTOS','Extrema','FAZER 250 ABS',1,2);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('ckfx1w3l19ufpbtp5c8g','NIPPON MOTOS','Extrema','FLUO ABS',1,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cjeiepjgeqjr20tkjdl','NIPPON MOTOS','Extrema','FAZER FZ15 ABS',0,1);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cyfsqecl432pmnt80tcu','NIPPON MOTOS','Extrema','LANDER 250 ABS',3,3);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c2o5q859q74t6p8d6i9','NIPPON MOTOS','Extrema','NMAX',2,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c0omt91r6krdqark4h2ie','NIPPON MOTOS','Extrema','R15 ABS',1,2);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cpkg0fgaloahp5chfgga','NIPPON MOTOS','Extrema','TÉNÉRÉ 700',1,0);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cktfxbbzz7lrunzojozx','NIPPON MOTOS','Extrema','XMAX 300',0,2);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('c14tbb6ywgkg5fx5ryfh','NIPPON MOTOS','Extrema','YAMAHA ZR',1,3);
INSERT INTO "Estoque" ("id","grupo","loja","modelo","chao","transito") VALUES ('cblf900apwy6kb3hrg5j','NIPPON MOTOS','Extrema','FACTOR 150 DX',2,0);

-- 8. Leads Nippon
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('co5hmuhpl6erlum7guc','2025/01',68,64,34.2,80,6.2,18.3) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('clzjj1ykjxmsd914dfxe','2025/02',64,60,37.7,56.5,15,15.7) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('c8ke12r8kqe95w9mieav','2025/03',79,71,43.5,68.4,8.5,8.4) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cqa9kceenwxrexera1y8','2025/04',61,45,28.4,50,13.3,11.6) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('clt345ctri5k5ua462dy','2025/05',63,57,45.9,84.6,0,27.3) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cpsajjj7wjta2ighj9y','2025/06',47,44,33.4,60,9.1,29) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cmb450v9fg9z0cm7omk','2025/07',50,49,46,81.2,8.2,25.6) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cy1ia8oelavuec3sqco','2025/08',65,59,33.6,70,6.8,6.8) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('c8jo2ebnhnk90wlgrykq','2025/09',65,57,36.1,68.8,7,6) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('ci1jtxewnmum9ubf5mkt','2025/10',72,66,29.5,60,4.5,31.5) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cwwp42klgzvs0kbv6w0n','2025/11',77,72,43.3,100,5.6,26.6) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('ctki7oqhscvikze0dto','2025/12',87,80,37,30,12.5,25.4) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cfrmh5t02w099q9mniis','2026/01',88,82,45.8,100,12.2,23.5) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('c7d83pmh32nsi5nqzfba','2026/02',101,93,28,70,5.4,20.5) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cztmo5dswbaknul56ymb','2026/03',104,98,45.4,73.3,8.2,18.1) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('cvgfeecvszg6odn687w','2026/04',87,81,40.3,64.7,4.9,7.5) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('c0052qsgslbb0nyh83b0en','2026/05',67,64,30.6,60,6.2,9.2) ON CONFLICT ("referencia") DO NOTHING;
INSERT INTO "LeadMensal" ("id","referencia","leads","leadsUnicos","tempoAtendMin","tcaPct","lcrGrupoPct","diasConversao") VALUES ('c9yzxinwdhmqv8jb915l','2026/06',22,21,45,100,0,0) ON CONFLICT ("referencia") DO NOTHING;

-- 9. NPS Vendas
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cut8ruqp13xl81j79kv3','2025/07','vendas',97.4,97.4,94,5,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cfroy7a08u2uvtv0tvky','2025/08','vendas',97.4,97.4,94,5,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cvlh4lb4mywaq15vflgt','2025/09','vendas',97.2,97.3,94,5,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cen0agdgt1df1osbfyd8','2025/10','vendas',97,97.2,94,5,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('c4pbcl6undkbqoyww8d8','2025/11','vendas',97.5,97.2,95,4,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cg5jfe4nqclme96dm32v','2025/12','vendas',96,96.8,93,6,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cobtgkdhnl8ewde98mt','2026/01','vendas',94.4,95.9,92,6,2);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cwhqkvex8lto560is7l','2026/02','vendas',91.2,93.9,88,9,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cvf9wta0lymnazr7uwwg','2026/03','vendas',93.9,93.2,91,7,2);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cl10ojb6m3flb4wia8t','2026/04','vendas',94.4,93.2,92,6,2);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('czczcrr4jl76is8u0x2','2026/05','vendas',95.8,94.7,93,6,1);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('ctcg8infdv7j46hjh1hs','2026/06','vendas',94.5,94.9,92,6,2);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cf1t9ev1t1mbz0jtjwu','2025/07','pos-vendas',89.4,89.4,87,10,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cwi6ha6j96tpkjtm0pbb','2025/08','pos-vendas',90.2,89.6,87,10,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cmrozco65ezh51d9r34u','2025/09','pos-vendas',87.7,89.1,85,11,4);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('c2tngk3ois761a0hz7bt','2025/10','pos-vendas',87.6,88.5,85,11,4);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('c0geek835a3ql5r3licfu','2025/11','pos-vendas',86.9,87.4,84,12,4);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('ckq4h3f1e4nehklluds2','2025/12','pos-vendas',89,87.8,86,11,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cphbgb4vxrtblgzallf','2026/01','pos-vendas',89,88.3,86,11,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('c4s2rf7ognf8njmdrv7u','2026/02','pos-vendas',90.2,89.4,87,10,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('ch3ll1r5mlhfeziye4c','2026/03','pos-vendas',89.8,89.7,87,10,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('ck6olc1y2x6wlf79q01','2026/04','pos-vendas',89,89.7,86,11,3);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('cz42rv03difnhglyruze','2026/05','pos-vendas',88.3,89,86,10,4);
INSERT INTO "NPSMensal" ("id","referencia","tipo","scoreMensal","scoreTrimestral","promotores","neutros","detratores") VALUES ('c74e11984bzspn09ziho','2026/06','pos-vendas',87.7,88.3,85,11,4);

SELECT 'Seed concluído com sucesso!' as status;